version: '2.4'
services:
  db:
    build: ./db
    image: shepher-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shepher
  web:
    build: ./
    image: shepher
    ports:
       - "8089:8089"
    depends_on:
       db:
         condition: service_healthy
       zookeeper:
         condition: service_started
  zookeeper:
    image: zookeeper
    expose:
       - 2181
       - 2888
       - 3888
