version: '2'
services:
  db: 
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  web:
    build: ./
    image: shepher
    ports:
       - "8089:8089"
    depends_on:
       - db
       - zookeeper
    links:
       - db
  zookeeper:
    image: zookeeper
    expose:
       - 2181
       - 2888
       - 3888
